[glossary#glossary]
= Glossary

Contract Endpoints ::
Off-chain functions used by a wallet to interact with a smart contract.

[[data-script]]Data Script ::
Piece of <<plutus-core,Plutus Core>> code which is part of a
<<script-output,script output>> and will be passed to the
<<validator-script,validator script>> as part of checking the validity of a
<<script-input,script input>>.

Extended UTxO ::
The ledger model on which the Plutus platform is based. Extends the traditional UTxO model
with <<data-script,data scripts>> and <<tx,transaction>> information

[[fungible-token]]Fungible Token ::
A <<custom-token,token>> that is interchangeable with other tokens.

Mockchain ::
A Cardano blockchain emulator which faithfully implements the Extended UTxO model.

Mock wallet ::
A wallet emulator which is used to interact with the mockchain

[[non-fungible-token]]Non-fungible Token ::
A <<custom-token,token>> that is not interchangeable with other tokens.

Off-chain code ::
Code written as part of a smart contract which executes off the chain, usually in a user's wallet.

On-chain code ::
Code written as part of a smart contract which executes on the chain during
<<tx,transaction>> validation.

[#plutus-core]
Plutus Core ::
A small functional programming language designed to run as on-chain code.

Plutus IR ::
An intermediate language that compiles to Plutus Core, for use as a target language for compiler writers.

Plutus Platform ::
The combined software support for writing smart contracts, including:
- libraries for writing off-chain code in Haskell.
- libraries for writing on-chain code in Plutus Tx.
- emulator support for testing smart contracts.

Plutus Playground ::
A browser based environment for writing and testing Plutus contracts.

Plutus Tx ::
A subset of Haskell which is compiled into Plutus Core.

[[pubkey-address]]Public Key Address ::
Possible address type for a <<transaction-output,transaction output>>.
In order to unlock funds at such an address, one has to prove owning the
corresponding private key.

[[pubkey-input]]Public Key Input ::
Type of <<transaction-input,transaction input>> collecting <<value,value>>
from a <<pubkey-output,public key output>>.
<<tx,Transactions>> with such an input must be signed by the owner
of the corresponding private key in order to be valid.

[[pubkey-output]]Public Key Output ::
A <<transaction-output,transaction output>>
which locks value at a <<pubkey-address,public key address>>:
A pair consisting of the <<pubkey-address,public key address>>
and the <<value,value>>.

[[redeemer-script]]Redeemer Script ::

[[script-address]]Script Address ::
Possible address type for a <<transaction-output,transaction output>>:
Hash of a <<validator-script,validator script>>.

[[script-input]]Script Input ::
Type of <<transaction-input,transaction input>> collecting <<value,value>>
from a <<script-output,script output>>.
Contains a <<redeemer-script,redeemer script>>.

[[script-output]]Script Output ::
A <<transaction-output,transaction output>>
which locks value at a <<script-address,script address>>: 
A triple consisting of the <<script-address,script address>>,
the <<value,value>>
and the <<data-script,data script>>.

[[custom-token]]Token ::
A custom <<value,value>> defined by a currency symbol and a token name.
Can be <<fungible-token,fungible>>, <<non-fungible-token,non-fungible>>
or mixed. Ada is a special kind of token with currency symbol and token name
both the empty bytestring.

[[tx]]Transaction ::
Collects <<value,value>> from zero or more <<transaction-input,transaction inputs>>
and redistributes that value to zero or more <<transaction-output,transaction outputs>>.
Can optionally forge new value.

[[transaction-input]]Transaction Input ::
Determines from where the <<value,value>>
redistributed by a <<tx,transaction>> is taken. 
Corresponding to the two <<transaction-output,output types>>,
there are two input types,
<<pubkey-input,public key inputs>> and
<<script-input,script inputs>>.

[[transaction-output]]Transaction Output ::
Determines how a <<tx,transaction>> distributes its 
<<transaction-input,inputs>>. There are two types,
<<pubkey-output,public key outputs>> and
<<script-output,script outputs>>.

[[validator-script]]Validator Script ::
Script to validate whether a <<tx,transaction>> is allowed to use a
<<script-output,script output>> as <<transaction-input,input>>.

[[value]]Value ::
Technically a map from currency symbols to maps from token symbols to integers.
Represents a collection of Ada and <<custom-token,tokens>> and is the "substance" being
redistributed by <<tx,transactions>>.
