# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@antora/asciidoc-loader-2.0.0" = {
      name = "_at_antora_slash_asciidoc-loader";
      packageName = "@antora/asciidoc-loader";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/asciidoc-loader/-/asciidoc-loader-2.0.0.tgz";
        sha512 = "kbpSBMM618Do5dXtG5mC5kk8VEXYDsciJ0orw7vrYeFzRBbR4Y4qpzbsQeuQNB4r2iLoztxErvg04SBb5CsGdQ==";
      };
    };
    "@antora/content-aggregator-2.0.0" = {
      name = "_at_antora_slash_content-aggregator";
      packageName = "@antora/content-aggregator";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/content-aggregator/-/content-aggregator-2.0.0.tgz";
        sha512 = "24JQSDQZ609yJHs7abIqF5FikNg0EWvFwBYck1Kbl5vRikmDTpSMBhhPKJhAVe4lREm6/FVYO7t9CEmjp69prA==";
      };
    };
    "@antora/content-classifier-2.0.0" = {
      name = "_at_antora_slash_content-classifier";
      packageName = "@antora/content-classifier";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/content-classifier/-/content-classifier-2.0.0.tgz";
        sha512 = "d1MB57X3AaXy30rw+dudxbJ2cdw/Uk1U4JxHbWIkdrEJKty2fbnBu3xjyb70qAv5G0ayovJpqZOaR+YwS0ibbQ==";
      };
    };
    "@antora/document-converter-2.0.0" = {
      name = "_at_antora_slash_document-converter";
      packageName = "@antora/document-converter";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/document-converter/-/document-converter-2.0.0.tgz";
        sha512 = "8slnLdeMxI4kU64fMsNp58HjpFYZ7chrl5tCYr1/4Jr00fVHwn8vx2YS1cKyowcrmb9uG6YI/pMNt9F3kjTtYA==";
      };
    };
    "@antora/expand-path-helper-1.0.0" = {
      name = "_at_antora_slash_expand-path-helper";
      packageName = "@antora/expand-path-helper";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/expand-path-helper/-/expand-path-helper-1.0.0.tgz";
        sha512 = "hg3y6M3OvRTb7jtLAnwwloYDxafbyKYttcf16kGCXvP7Wqosh7c+Ag+ltaZ7VSebpzpphO/umb/BXdpU7rxapw==";
      };
    };
    "@antora/navigation-builder-2.0.0" = {
      name = "_at_antora_slash_navigation-builder";
      packageName = "@antora/navigation-builder";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/navigation-builder/-/navigation-builder-2.0.0.tgz";
        sha512 = "tuI2dNDy9sqgkHoiqn52M0lWrxxOafrEUIPSskjyGf0MjFP3pBPKnHiBmAl2r+NhXCAfcIb5khe4rSS18bfiVA==";
      };
    };
    "@antora/page-composer-2.0.0" = {
      name = "_at_antora_slash_page-composer";
      packageName = "@antora/page-composer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/page-composer/-/page-composer-2.0.0.tgz";
        sha512 = "1I0vhO6UCyNJRLYICTU+jCTEmkHeJ13tao0nfOOAiSyamDkyX7vM935qfzGBjwZdur8Clq4jpiCuvFTmXMtIfQ==";
      };
    };
    "@antora/playbook-builder-2.0.0" = {
      name = "_at_antora_slash_playbook-builder";
      packageName = "@antora/playbook-builder";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/playbook-builder/-/playbook-builder-2.0.0.tgz";
        sha512 = "uLU4+rpIRZiMit8s1lkbiz5L5V8cPL40RJMRHFb4B7k2PXbvNiZZAMHZBeFgVwfJIKmKAIeUCDgOHgiBIlFc+A==";
      };
    };
    "@antora/redirect-producer-2.0.0" = {
      name = "_at_antora_slash_redirect-producer";
      packageName = "@antora/redirect-producer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/redirect-producer/-/redirect-producer-2.0.0.tgz";
        sha512 = "qlRPGNAhtbIOWK9XHEdH4Iiaz1/8SBvm5rK46R4YinjZqMibMehOfFoIdRf2qsE9mfOsYKwKUSF8Jnv/emXuJw==";
      };
    };
    "@antora/site-mapper-2.0.0" = {
      name = "_at_antora_slash_site-mapper";
      packageName = "@antora/site-mapper";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/site-mapper/-/site-mapper-2.0.0.tgz";
        sha512 = "rPpDLuJbM7c0fNpzf95qrxsjzNAXuyACXE+FXUOwmFp3SYIFGEWATLk1MMNes7SfLAchMMVwjEr1Uii3D5+/Mw==";
      };
    };
    "@antora/site-publisher-2.0.0" = {
      name = "_at_antora_slash_site-publisher";
      packageName = "@antora/site-publisher";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/site-publisher/-/site-publisher-2.0.0.tgz";
        sha512 = "kjKfQSEpcLiw653h9IzCG+L9sYm/v9GXAcbzXN1IYoNPO1Od0EPQ2RXGviqeQNYcWJLyRq48cQpNx7o2/KqVag==";
      };
    };
    "@antora/ui-loader-2.0.0" = {
      name = "_at_antora_slash_ui-loader";
      packageName = "@antora/ui-loader";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antora/ui-loader/-/ui-loader-2.0.0.tgz";
        sha512 = "CaD+Dp13G7EZhEr6Jg6OEvPHjJZ2FROXwdaY4XP+vBrKmI+QZwS3V+uG0NYbCRxhR1W8N8CYm5hc1UTvGH19cA==";
      };
    };
    "@babel/runtime-7.5.4" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.5.4.tgz";
        sha512 = "Na84uwyImZZc3FKf4aUF1tysApzwf3p2yuFBIyBfbzT5glzKTdvYI4KVW4kcgjrzoGUjC7w3YyCHcJKaRxsr2Q==";
      };
    };
    "@iarna/toml-2.2.3" = {
      name = "_at_iarna_slash_toml";
      packageName = "@iarna/toml";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iarna/toml/-/toml-2.2.3.tgz";
        sha512 = "FmuxfCuolpLl0AnQ2NHSzoUKWEJDFl63qXjzdoWBVyFCXzMGm1spBzk7LeHNoVCiWCF7mRVms9e6jEV9+MoPbg==";
      };
    };
    "@sindresorhus/is-0.14.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-0.14.0.tgz";
        sha512 = "9NET910DNaIPngYnLLPeg+Ogzqsi9uM4mSboU5y6p8S5DzMTVEsJZrawi+BoDNUVBa2DhJqQYUFvMDfgU062LQ==";
      };
    };
    "@szmarczak/http-timer-1.1.2" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-1.1.2.tgz";
        sha512 = "XIB2XbzHTN6ieIjfIMV9hlVcfPU26s2vafYWQcZHWXHOxiaRZYEDKEwdl129Zyg50+foYV2jCgtrqSA6qNuNSA==";
      };
    };
    "append-buffer-1.0.2" = {
      name = "append-buffer";
      packageName = "append-buffer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/append-buffer/-/append-buffer-1.0.2.tgz";
        sha1 = "d8220cf466081525efea50614f3de6514dfa58f1";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "asciidoctor.js-1.5.9" = {
      name = "asciidoctor.js";
      packageName = "asciidoctor.js";
      version = "1.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/asciidoctor.js/-/asciidoctor.js-1.5.9.tgz";
        sha512 = "k5JgwyV82TsiCpnYbDPReuHhzf/vRUt6NaZ+OGywkDDGeGG/CPfvN2Gd1MJ0iIZKDyuk4iJHOdY/2x1KBrWMzA==";
      };
    };
    "async-lock-1.2.2" = {
      name = "async-lock";
      packageName = "async-lock";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-lock/-/async-lock-1.2.2.tgz";
        sha512 = "uczz62z2fMWOFbyo6rG4NlV2SdxugJT6sZA2QcfB1XaSjEiOh8CuOb/TttyMnYQCda6nkWecJe465tGQDPJiKw==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-0.0.2" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz";
        sha1 = "024f0f72afa25b75f9c0ee73cd4f55ec1bed9784";
      };
    };
    "benchmark-1.0.0" = {
      name = "benchmark";
      packageName = "benchmark";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz";
        sha1 = "2f1e2fa4c359f11122aa183082218e957e390c73";
      };
    };
    "bl-2.2.0" = {
      name = "bl";
      packageName = "bl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-2.2.0.tgz";
        sha512 = "wbgvOpqopSr7uq6fJrLH8EsvYMJf9gzfo2jCsL2eTy75qXPukA4pCgHamOQkZtY5vmfVtjB+P3LNlMHW5CEZXA==";
      };
    };
    "bops-0.0.7" = {
      name = "bops";
      packageName = "bops";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bops/-/bops-0.0.7.tgz";
        sha1 = "b4a0a5a839a406454af0fe05a8b91a7a766a54e2";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "buffer-equal-1.0.0" = {
      name = "buffer-equal";
      packageName = "buffer-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal/-/buffer-equal-1.0.0.tgz";
        sha1 = "59616b498304d556abd466966b22eeda3eca5fbe";
      };
    };
    "cache-directory-2.0.0" = {
      name = "cache-directory";
      packageName = "cache-directory";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-directory/-/cache-directory-2.0.0.tgz";
        sha512 = "7YKEapH+2Uikde8hySyfobXBqPKULDyHNl/lhKm7cKf/GJFdG/tU/WpLrOg2y9aUrQrWUilYqawFIiGJPS6gDA==";
      };
    };
    "cacheable-request-6.1.0" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-6.1.0.tgz";
        sha512 = "Oj3cAGPCqOZX7Rz64Uny2GYAZNliQSqfbePrgAQ1wKAihYmCUnraBtJtKcGR4xz7wF+LoJC+ssFZvv5BgF9Igg==";
      };
    };
    "camelcase-5.3.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz";
        sha512 = "L28STB170nwWS63UjtlEOE3dldQApaJXZkOI1uMFfzf3rRuPegHaHesyee+YxQ+W6SvRDQV6UrdOdRiR153wJg==";
      };
    };
    "camelcase-keys-5.2.0" = {
      name = "camelcase-keys";
      packageName = "camelcase-keys";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-5.2.0.tgz";
        sha512 = "mSM/OQKD1HS5Ll2AXxeaHSdqCGC/QQ8IrgTbKYA/rxnC36thBKysfIr9+OVBWuW17jyZF4swHkjtglawgBmVFg==";
      };
    };
    "clean-git-ref-1.0.3" = {
      name = "clean-git-ref";
      packageName = "clean-git-ref";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-git-ref/-/clean-git-ref-1.0.3.tgz";
        sha1 = "5325dc839eab01c974ae0e97f5734782750f88ec";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha1 = "1b7f4b9f591f1e8f83670401600345a02887435f";
      };
    };
    "clone-buffer-1.0.0" = {
      name = "clone-buffer";
      packageName = "clone-buffer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-buffer/-/clone-buffer-1.0.0.tgz";
        sha1 = "e3e25b207ac4e701af721e2cb5a16792cac3dc58";
      };
    };
    "clone-response-1.0.2" = {
      name = "clone-response";
      packageName = "clone-response";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-response/-/clone-response-1.0.2.tgz";
        sha1 = "d1dc973920314df67fbeb94223b4ee350239e96b";
      };
    };
    "clone-stats-1.0.0" = {
      name = "clone-stats";
      packageName = "clone-stats";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-stats/-/clone-stats-1.0.0.tgz";
        sha1 = "b3782dff8bb5474e18b9b6bf0fdfe782f8777680";
      };
    };
    "cloneable-readable-1.1.3" = {
      name = "cloneable-readable";
      packageName = "cloneable-readable";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cloneable-readable/-/cloneable-readable-1.1.3.tgz";
        sha512 = "2EF8zTQOxYq70Y4XKtorQupqF0m49MBz2/yf5Bj+MHjvpG3Hy7sImifnqD6UA+TKYxeSV+u6qqQPawN5UvnpKQ==";
      };
    };
    "commander-2.20.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.0.tgz";
        sha512 = "7j2y+40w61zy6YC2iRNpUe/NwhNyoXrYpHMrSunaMG64nRnaf96zO/KMQR4OyN/UnE5KLyEBnKHd4aG3rskjpQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "convert-source-map-1.6.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.6.0.tgz";
        sha512 = "eFu7XigvxdZ1ETfbgPBohgyQ/Z++C0eEhTor0qRwBw9unw+L0/6V8wkSuGgzdThkiS5lSpdptOQPD8Ak40a+7A==";
      };
    };
    "convict-4.4.1" = {
      name = "convict";
      packageName = "convict";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/convict/-/convict-4.4.1.tgz";
        sha512 = "celpR4hOWWwb/S8azhzgQwDon6muAJlNe2LTLeOGyoSgH390TsaqoieAe9BLbAv7+9wNfG7DTA2q3IfFp2viKw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crc-32-1.2.0" = {
      name = "crc-32";
      packageName = "crc-32";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc-32/-/crc-32-1.2.0.tgz";
        sha512 = "1uBwHxF+Y/4yF5G48fwnKq6QsIXheor3ZLPT80yGBV1oEUwpPojlEhQbWKVw1VwcTQyMGHK1/XMmTjmlsmTTGA==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha1 = "80a4dd323748384bfa248083622aedec982adff3";
      };
    };
    "deep-freeze-0.0.1" = {
      name = "deep-freeze";
      packageName = "deep-freeze";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-freeze/-/deep-freeze-0.0.1.tgz";
        sha1 = "3a0b0005de18672819dfd38cd31f91179c893e84";
      };
    };
    "defer-to-connect-1.0.2" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-1.0.2.tgz";
        sha512 = "k09hcQcTDY+cwgiwa6PYKLm3jlagNzQ+RSvhjzESOGOx+MNOuXkxTfEvPrO1IOQ81tArCFYQgi631clB70RpQw==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "diff-3.5.0" = {
      name = "diff";
      packageName = "diff";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-3.5.0.tgz";
        sha512 = "A46qtFgd+g7pDZinpnwiRJtxbC1hpgf0uzP3iG89scHk0AUC7A1TGxf5OiiOUv/JMZR8GOt8hL900hV0bOy5xA==";
      };
    };
    "diff-lines-1.1.1" = {
      name = "diff-lines";
      packageName = "diff-lines";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff-lines/-/diff-lines-1.1.1.tgz";
        sha512 = "Oo5JzEEriF/+T0usOeRP5yOzr6SWvni2rrxvIgijMZSxPcEvf8JOvCO5GpnWwkte7fcOgnue/f5ECg1H9lMPCw==";
      };
    };
    "duplexer-0.1.1" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.1.tgz";
        sha1 = "ace6ff808c1ce66b57d1ebf97977acb02334cfc1";
      };
    };
    "duplexer3-0.1.4" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.4.tgz";
        sha1 = "ee01dd1cac0ed3cbc7fdbea37dc0a8f1ce002ce2";
      };
    };
    "duplexify-3.7.1" = {
      name = "duplexify";
      packageName = "duplexify";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexify/-/duplexify-3.7.1.tgz";
        sha512 = "07z8uv2wMyS51kKhD1KsdXJg5WQ6t93RneqRxUHnskXVtlYYkLqM0gqStQZ3pj073g687jPCHrqNfCzawLYh5g==";
      };
    };
    "end-of-stream-1.4.1" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.1.tgz";
        sha512 = "1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "event-stream-3.3.4" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz";
        sha1 = "4ab4c9a0f5a54db9338b4c34d86bfce8f4b35571";
      };
    };
    "exit-on-epipe-1.0.1" = {
      name = "exit-on-epipe";
      packageName = "exit-on-epipe";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit-on-epipe/-/exit-on-epipe-1.0.1.tgz";
        sha512 = "h2z5mrROTxce56S+pnvAV890uu7ls7f1kEvVGJbw1OlFH3/mlJ5bkXu0KRyW94v37zzHPiUd55iLn3DA7TjWpw==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha1 = "25c7c89cb1f9077f8891bbe61d8f390eae256f1e";
      };
    };
    "flush-write-stream-1.1.1" = {
      name = "flush-write-stream";
      packageName = "flush-write-stream";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flush-write-stream/-/flush-write-stream-1.1.1.tgz";
        sha512 = "3Z4XhFZ3992uIq0XOqb9AreonueSYphE6oYbpt5+3u06JWklbsPkNv3ZKkP9Bz/r+1MWCaMoSQ28P85+1Yc77w==";
      };
    };
    "from-0.1.7" = {
      name = "from";
      packageName = "from";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/from/-/from-0.1.7.tgz";
        sha1 = "83c60afc58b9c56997007ed1a768b3ab303a44fe";
      };
    };
    "fs-extra-7.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-7.0.1.tgz";
        sha512 = "YJDaCJZEnBmcbw13fvdAM9AwNOJwOzrE4pqMqBq5nFiEqXUqHwlK4B+3pUw6JNvfSPtX05xFHtYy/1ni01eGCw==";
      };
    };
    "fs-mkdirp-stream-1.0.0" = {
      name = "fs-mkdirp-stream";
      packageName = "fs-mkdirp-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-mkdirp-stream/-/fs-mkdirp-stream-1.0.0.tgz";
        sha1 = "0b7815fc3201c6a69e14db98ce098c16935259eb";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-stream-4.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    "get-stream-5.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-5.1.0.tgz";
        sha512 = "EXr1FOzrzTfGeL0gQdeFEvOMm2mzMOglyiOXSTpPC+iAjAKftbr3jpCMWynogwYnM+eSj9sHGc6wjIcDvYiygw==";
      };
    };
    "git-apply-delta-0.0.7" = {
      name = "git-apply-delta";
      packageName = "git-apply-delta";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/git-apply-delta/-/git-apply-delta-0.0.7.tgz";
        sha1 = "fb76ae144540d79440b52b31de03e63c993c7219";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "glob-7.1.4" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.4.tgz";
        sha512 = "hkLPepehmnKk41pUGm3sYxoFs/umurYfYJCerbXEyFIWcAzvpipAgVkBqqT9RBKMGjnq6kMuyYwha6csxbiM1A==";
      };
    };
    "glob-parent-3.1.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-3.1.0.tgz";
        sha1 = "9e6af6299d8d3bd2bd40430832bd113df906c5ae";
      };
    };
    "glob-stream-6.1.0" = {
      name = "glob-stream";
      packageName = "glob-stream";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-stream/-/glob-stream-6.1.0.tgz";
        sha1 = "7045c99413b3eb94888d83ab46d0b404cc7bdde4";
      };
    };
    "globalyzer-0.1.4" = {
      name = "globalyzer";
      packageName = "globalyzer";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalyzer/-/globalyzer-0.1.4.tgz";
        sha512 = "LeguVWaxgHN0MNbWC6YljNMzHkrCny9fzjmEUdnF1kQ7wATFD1RHFRqA1qxaX2tgxGENlcxjOflopBwj3YZiXA==";
      };
    };
    "globrex-0.1.2" = {
      name = "globrex";
      packageName = "globrex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/globrex/-/globrex-0.1.2.tgz";
        sha512 = "uHJgbwAMwNFf5mLst7IWLNg14x1CkeqglJb/K3doi4dw6q2IvAAmM/Y81kevy83wP+Sst+nutFTYOGg3d1lsxg==";
      };
    };
    "got-9.6.0" = {
      name = "got";
      packageName = "got";
      version = "9.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-9.6.0.tgz";
        sha512 = "R7eWptXuGYxwijs0eV+v3o6+XH1IqVK8dJOEecQfTmkncw9AV4dcw/Dhxi8MdlqPthxxpZyizMzyg8RTmEsG+Q==";
      };
    };
    "graceful-fs-4.2.0" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.0.tgz";
        sha512 = "jpSvDPV4Cq/bgtpndIWbI5hmYxhQGHPC4d4cqBPb4DLniCfhJokdXhwhaDuLBGLQdvvRum/UiX6ECVIPvDXqdg==";
      };
    };
    "gulp-vinyl-zip-2.1.2" = {
      name = "gulp-vinyl-zip";
      packageName = "gulp-vinyl-zip";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gulp-vinyl-zip/-/gulp-vinyl-zip-2.1.2.tgz";
        sha512 = "wJn09jsb8PyvUeyFF7y7ImEJqJwYy40BqL9GKfJs6UGpaGW9A+N68Q+ajsIpb9AeR6lAdjMbIdDPclIGo1/b7Q==";
      };
    };
    "handlebars-4.1.2" = {
      name = "handlebars";
      packageName = "handlebars";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/handlebars/-/handlebars-4.1.2.tgz";
        sha512 = "nvfrjqvt9xQ8Z/w0ijewdD/vvWDTOweBUm96NTr66Wfvo1mJenBLwcYmPs3TIBP5ruzYGD7Hx/DaM9RmhroGPw==";
      };
    };
    "has-symbols-1.0.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.0.tgz";
        sha1 = "ba1a8f1af2a0fc39650f5c850367704122063b44";
      };
    };
    "http-cache-semantics-4.0.3" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.0.3.tgz";
        sha512 = "TcIMG3qeVLgDr1TEd2XvHaTnMPwYQUQMIBLy+5pLSDKYFc7UIqj39w8EGzZkaxoLv/l2K8HaI0t5AVA+YYgUew==";
      };
    };
    "ignore-5.1.2" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.1.2.tgz";
        sha512 = "vdqWBp7MyzdmHkkRWV5nY+PfGRbYbahfuvsBCh277tq+w9zyNi7h5CYJCK0kmzti9kU+O/cB7sE8HvKv6aXAKQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-absolute-1.0.0" = {
      name = "is-absolute";
      packageName = "is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute/-/is-absolute-1.0.0.tgz";
        sha512 = "dOWoqflvcydARa360Gvv18DZ/gRuHKi2NU/wU5X1ZFzdYfH29nkiNZsF3mp4OJ3H4yo9Mx8A/uAGNzpzPN3yBA==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-3.1.0" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-3.1.0.tgz";
        sha1 = "7ba5ae24217804ac70707b96922567486cc3e84a";
      };
    };
    "is-negated-glob-1.0.0" = {
      name = "is-negated-glob";
      packageName = "is-negated-glob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negated-glob/-/is-negated-glob-1.0.0.tgz";
        sha1 = "6910bca5da8c95e784b5751b976cf5a10fee36d2";
      };
    };
    "is-relative-1.0.0" = {
      name = "is-relative";
      packageName = "is-relative";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-relative/-/is-relative-1.0.0.tgz";
        sha512 = "Kw/ReK0iqwKeu0MITLFuj0jbPAmEiOsIwyIXvvbfa6QfmN9pkD1M+8pdk7Rl/dTKbH34/XBFMbgD4iMJhLQbGA==";
      };
    };
    "is-unc-path-1.0.0" = {
      name = "is-unc-path";
      packageName = "is-unc-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unc-path/-/is-unc-path-1.0.0.tgz";
        sha512 = "mrGpVd0fs7WWLfVsStvgF6iEJnbjDFZh9/emhRDcGWTduTfNHd9CHeUwH3gYIjdbwo4On6hunkztwOaAw0yllQ==";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "is-valid-glob-1.0.0" = {
      name = "is-valid-glob";
      packageName = "is-valid-glob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-valid-glob/-/is-valid-glob-1.0.0.tgz";
        sha1 = "29bf3eff701be2d4d315dbacc39bc39fe8f601aa";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isomorphic-git-0.47.0" = {
      name = "isomorphic-git";
      packageName = "isomorphic-git";
      version = "0.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-git/-/isomorphic-git-0.47.0.tgz";
        sha512 = "oea4It03KvuJrEbwYGMrRmlY+Wh7a/J/jBYKezkiUW/s6GrcAePOCnpfLR8TXkHiASZlEHCgckMd7uMAfJ9w/w==";
      };
    };
    "js-yaml-3.13.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz";
        sha512 = "YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==";
      };
    };
    "json-buffer-3.0.0" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.0.tgz";
        sha1 = "5b1f397afc75d677bde8bcfc0e47e1f9a3d9a898";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha1 = "9db7b59496ad3f3cfef30a75142d2d930ad72651";
      };
    };
    "json5-1.0.1" = {
      name = "json5";
      packageName = "json5";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-1.0.1.tgz";
        sha512 = "aKS4WQjPenRxiQsC93MNfjx+nbF4PAdYzmd/1JIj8HYzqfbu86beTuNgXDzPknWk0n0uARlyewZo4s++ES36Ow==";
      };
    };
    "json5-2.1.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.1.0.tgz";
        sha512 = "8Mh9h6xViijj36g7Dxi+Y4S6hNGV96vcJZr/SrlHh1LR/pEn/8j/+qIBbs44YKl69Lrfctp4QD+AdWLTMqEZAQ==";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "keyv-3.1.0" = {
      name = "keyv";
      packageName = "keyv";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-3.1.0.tgz";
        sha512 = "9ykJ/46SN/9KPM/sichzQ7OvXyGDYKGTaDlKMGCAlg2UK8KRy4jb0d8sFc+0Tt0YYnThq8X2RZgCg74RPxgcVA==";
      };
    };
    "lazystream-1.0.0" = {
      name = "lazystream";
      packageName = "lazystream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazystream/-/lazystream-1.0.0.tgz";
        sha1 = "f6995fe0f820392f61396be89462407bb77168e4";
      };
    };
    "lead-1.0.0" = {
      name = "lead";
      packageName = "lead";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lead/-/lead-1.0.0.tgz";
        sha1 = "6f14f99a37be3a9dd784f5495690e5903466ee42";
      };
    };
    "lodash-4.17.14" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.14.tgz";
        sha512 = "mmKYbW3GLuJeX+iGP+Y7Gp1AiGHGbXHCOh/jZmrawMmsE7MS4znI3RL2FsjbqOyMayHInjOeykW7PEajUk1/xw==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "lowercase-keys-2.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-2.0.0.tgz";
        sha512 = "tqNXrS78oMOE73NMxK4EMLQsQowWf8jKooH9g7xPavRT706R6bkQJ6DY2Te7QukaZsulxa30wQ7bk0pm4XiHmA==";
      };
    };
    "map-obj-3.1.0" = {
      name = "map-obj";
      packageName = "map-obj";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-obj/-/map-obj-3.1.0.tgz";
        sha512 = "Xg1iyYz/+iIW6YoMldux47H/e5QZyDSB41Kb0ev+YYHh3FJnyyzY0vTk/WbVeWcCvdXd70cOriUBmhP8alUFBA==";
      };
    };
    "map-stream-0.1.0" = {
      name = "map-stream";
      packageName = "map-stream";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-stream/-/map-stream-0.1.0.tgz";
        sha1 = "e56aa94c4c8055a16404a0674b78f215f7c8e194";
      };
    };
    "marky-1.2.1" = {
      name = "marky";
      packageName = "marky";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/marky/-/marky-1.2.1.tgz";
        sha512 = "md9k+Gxa3qLH6sUKpeC2CNkJK/Ld+bEz5X96nYwloqphQE0CKCVEKco/6jxEZixinqNdz5RFi/KaCyfbMDMAXQ==";
      };
    };
    "matcher-1.1.1" = {
      name = "matcher";
      packageName = "matcher";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/matcher/-/matcher-1.1.1.tgz";
        sha512 = "+BmqxWIubKTRKNWx/ahnCkk3mG8m7OturVlqq6HiojGJTd5hVYbgZm6WzcYPCoB+KBT4Vd6R7WSRG2OADNaCjg==";
      };
    };
    "mime-db-1.40.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.40.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.40.0.tgz";
        sha512 = "jYdeOMPy9vnxEqFRRo6ZvTZ8d9oPb+k18PKoYNYUe2stVEBPPwsln/qWzdbmaIvnhZ9v2P+CuecK+fpUfsV2mA==";
      };
    };
    "mime-types-2.1.24" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.24.tgz";
        sha512 = "WaFHS3MCl5fapm3oLxU4eYDw77IQM2ACcxQ9RIxfaC3ooc6PFuBMGZZsYpvoXS5D5QTWPieo1jjLdAm3TBP3cQ==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimatch-all-1.1.0" = {
      name = "minimatch-all";
      packageName = "minimatch-all";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch-all/-/minimatch-all-1.1.0.tgz";
        sha1 = "40c496a27a2e128d19bf758e76bb01a0c7145787";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "minimisted-2.0.0" = {
      name = "minimisted";
      packageName = "minimisted";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimisted/-/minimisted-2.0.0.tgz";
        sha512 = "oP88Dw3LK/pdrKyMdlbmg3W50969UNr4ctISzJfPl+YPYHTAOrS+dihXnsgRNKSRIzDsrnV3eE2CCVlZbpOKdQ==";
      };
    };
    "moment-2.22.2" = {
      name = "moment";
      packageName = "moment";
      version = "2.22.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.22.2.tgz";
        sha1 = "3c257f9839fc0e93ff53149632239eb90783ff66";
      };
    };
    "multi-progress-2.0.0" = {
      name = "multi-progress";
      packageName = "multi-progress";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multi-progress/-/multi-progress-2.0.0.tgz";
        sha1 = "29ccb42cf24874b1c6384f03127ce5dff7b22f2c";
      };
    };
    "neo-async-2.6.1" = {
      name = "neo-async";
      packageName = "neo-async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.1.tgz";
        sha512 = "iyam8fBuCUpWeKPGpaNMetEocMt364qkCsfL9JuhjXX6dRnguRVOfk2GZaDpPjcOKiiXCPINZC1GczQ7iTq3Zw==";
      };
    };
    "nick-0.1.3" = {
      name = "nick";
      packageName = "nick";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/nick/-/nick-0.1.3.tgz";
        sha1 = "d8a30b7da789d417e0baa5437f33c487be9b6020";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "normalize-url-4.3.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-4.3.0.tgz";
        sha512 = "0NLtR71o4k6GLP+mr6Ty34c5GA6CMoEsncKJxvQd8NzPxaHRJNnb5gZE8R1XF4CPIS7QPHLJ74IFszwtNVAHVQ==";
      };
    };
    "now-and-later-2.0.1" = {
      name = "now-and-later";
      packageName = "now-and-later";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/now-and-later/-/now-and-later-2.0.1.tgz";
        sha512 = "KGvQ0cB70AQfg107Xvs/Fbu+dGmZoTRJp2TaPwcwQm3/7PteUyN2BCgk8KBMPGBUXZdVwyWS8fDCGFygBm19UQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "opal-runtime-1.0.11" = {
      name = "opal-runtime";
      packageName = "opal-runtime";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/opal-runtime/-/opal-runtime-1.0.11.tgz";
        sha512 = "L+6pnRvXPlDtbamBRnJAnB9mEMXmsIQ/b+0r/2xJ5/n/nxheEkLo+Pm5QNQ08LEbEN9TI6/kedhIspqRRu6tXA==";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "ordered-read-streams-1.0.1" = {
      name = "ordered-read-streams";
      packageName = "ordered-read-streams";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ordered-read-streams/-/ordered-read-streams-1.0.1.tgz";
        sha1 = "77c0cb37c41525d64166d990ffad7ec6a0e1363e";
      };
    };
    "p-cancelable-1.1.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-1.1.0.tgz";
        sha512 = "s73XxOZ4zpt1edZYZzvhqFa6uvQc1vwUa0K0BdtIZgQMAJj9IbebH+JkgKZc9h+B05PKHLOTl4ajG1BmNrVZlw==";
      };
    };
    "pako-1.0.10" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.10.tgz";
        sha512 = "0DTvPVU3ed8+HNXOu5Bs+o//Mbdj9VNQMUOe9oKCwh8l0GNwpTDMKCWbRjgtD291AWnkAgkqA/LOnQS8AmS1tw==";
      };
    };
    "path-dirname-1.0.2" = {
      name = "path-dirname";
      packageName = "path-dirname";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-dirname/-/path-dirname-1.0.2.tgz";
        sha1 = "cc33d24d525e099a5388c0336c6e32b9160609e0";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pause-stream-0.0.11" = {
      name = "pause-stream";
      packageName = "pause-stream";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz";
        sha1 = "fe5a34b0cbce12b5aa6a2b403ee2e73b602f1445";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha1 = "7a57eb550a6783f9115331fcf4663d5c8e007a50";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "prepend-http-2.0.0" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-2.0.0.tgz";
        sha1 = "e92434bfa5ea8c19f41cdfd401d741a3c819d897";
      };
    };
    "printj-1.1.2" = {
      name = "printj";
      packageName = "printj";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/printj/-/printj-1.1.2.tgz";
        sha512 = "zA2SmoLaxZyArQTOPj5LXecR+RagfPSU5Kw1qP+jkWeNlrq+eJZyY2oS68SU1Z/7/myXM4lo9716laOFAVStCQ==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "progress-1.1.8" = {
      name = "progress";
      packageName = "progress";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-1.1.8.tgz";
        sha1 = "e260c78f6161cdd9b0e56cc3e0a85de17c7a57be";
      };
    };
    "pump-2.0.1" = {
      name = "pump";
      packageName = "pump";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-2.0.1.tgz";
        sha512 = "ruPMNRkN3MHP1cWJc9OWr+T/xDP0jhXYCLfJcBuX54hhfIBnaQmAUMfDcG4DM5UMWByBbJY69QSphm3jtDKIkA==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "pumpify-1.5.1" = {
      name = "pumpify";
      packageName = "pumpify";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pumpify/-/pumpify-1.5.1.tgz";
        sha512 = "oClZI37HvuUJJxSKKrC17bZ9Cu0ZYhEAGPsPUy9KlMUmv9dKX2o77RUmq7f3XjIxbwyGwYzbzQ1L2Ks8sIradQ==";
      };
    };
    "queue-4.5.1" = {
      name = "queue";
      packageName = "queue";
      version = "4.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue/-/queue-4.5.1.tgz";
        sha512 = "AMD7w5hRXcFSb8s9u38acBZ+309u6GsiibP4/0YacJeaurRshogB7v/ZcVPxP5gD5+zIw6ixRHdutiYUJfwKHw==";
      };
    };
    "quick-lru-1.1.0" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-1.1.0.tgz";
        sha1 = "4360b17c61136ad38078397ff11416e186dcfbb8";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readable-stream-3.4.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.4.0.tgz";
        sha512 = "jItXPLmrSR8jmTRmRWJXCnGJsfy85mB3Wd/uINMXA65yrnFo0cPClFIUWzo2najVNSl+mx7/4W8ttlLWJe99pQ==";
      };
    };
    "regenerator-runtime-0.13.2" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.2.tgz";
        sha512 = "S/TQAZJO+D3m9xeN1WTI8dLKBBiRgXBlTJvbWjCThHWZj9EvHK70Ff50/tYj2J/fvBY6JtFVwRuazHN2E7M9BA==";
      };
    };
    "remove-bom-buffer-3.0.0" = {
      name = "remove-bom-buffer";
      packageName = "remove-bom-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-bom-buffer/-/remove-bom-buffer-3.0.0.tgz";
        sha512 = "8v2rWhaakv18qcvNeli2mZ/TMTL2nEyAKRvzo1WtnZBl15SHyEhrCu2/xKlJyUFKHiHgfXIyuY6g2dObJJycXQ==";
      };
    };
    "remove-bom-stream-1.2.0" = {
      name = "remove-bom-stream";
      packageName = "remove-bom-stream";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-bom-stream/-/remove-bom-stream-1.2.0.tgz";
        sha1 = "05f1a593f16e42e1fb90ebf59de8e569525f9523";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "replace-ext-1.0.0" = {
      name = "replace-ext";
      packageName = "replace-ext";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/replace-ext/-/replace-ext-1.0.0.tgz";
        sha1 = "de63128373fcbf7c3ccfa4de5a480c45a67958eb";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "resolve-options-1.1.0" = {
      name = "resolve-options";
      packageName = "resolve-options";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-options/-/resolve-options-1.1.0.tgz";
        sha1 = "32bb9e39c06d67338dc9378c0d6d6074566ad131";
      };
    };
    "responselike-1.0.2" = {
      name = "responselike";
      packageName = "responselike";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz";
        sha1 = "918720ef3b631c5642be068f15ade5a46f4ba1e7";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "simple-concat-1.0.0" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.0.tgz";
        sha1 = "7344cbb8b6e26fb27d66b2fc86f9f6d5997521c6";
      };
    };
    "simple-get-3.0.3" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-3.0.3.tgz";
        sha512 = "Wvre/Jq5vgoz31Z9stYWPLn0PqRqmBDpFSdypAnHu5AvRVCYPRYGnvryNLiXu8GOBNDH82J2FRHUGMjjHUpXFw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "split-0.3.3" = {
      name = "split";
      packageName = "split";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-0.3.3.tgz";
        sha1 = "cd0eea5e63a211dfff7eb0f091c4133e2d0dd28f";
      };
    };
    "split2-3.1.1" = {
      name = "split2";
      packageName = "split2";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split2/-/split2-3.1.1.tgz";
        sha512 = "emNzr1s7ruq4N+1993yht631/JH+jaj0NYBosuKmLcq+JkGQ9MmTw1RB1fGaTCzUuseRIClrlSLHRNYGwWQ58Q==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stream-combiner-0.0.4" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner/-/stream-combiner-0.0.4.tgz";
        sha1 = "4d5e433c185261dde623ca3f44c586bcf5c4ad14";
      };
    };
    "stream-shift-1.0.0" = {
      name = "stream-shift";
      packageName = "stream-shift";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-shift/-/stream-shift-1.0.0.tgz";
        sha1 = "d5c752825e5367e786f78e18e445ea223a155952";
      };
    };
    "stream-source-0.3.5" = {
      name = "stream-source";
      packageName = "stream-source";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-source/-/stream-source-0.3.5.tgz";
        sha512 = "ZuEDP9sgjiAwUVoDModftG0JtYiLUV8K4ljYD1VyUMRWtbVf92474o4kuuul43iZ8t/hRuiDAx1dIJSvirrK/g==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.2.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.2.0.tgz";
        sha512 = "6YqyX6ZWEYguAxgZzHGL7SsCeGx3V2TtOTqZz1xSTSWnqsbWwbptafNyvf/ACquZUXV3DANr5BDIwNYe1mN42w==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 = "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "through2-3.0.1" = {
      name = "through2";
      packageName = "through2";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-3.0.1.tgz";
        sha512 = "M96dvTalPT3YbYLaKaCuwu+j06D/8Jfib0o/PxbVt6Amhv3dUAtW6rTV1jPgJSBG83I/e04Y6xkVdVhSRhi0ww==";
      };
    };
    "through2-filter-3.0.0" = {
      name = "through2-filter";
      packageName = "through2-filter";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2-filter/-/through2-filter-3.0.0.tgz";
        sha512 = "jaRjI2WxN3W1V8/FMZ9HKIBXixtiqs3SQSX4/YGIiP3gL6djW48VoZq9tDqeCWs3MT8YY5wb/zli8VW8snY1CA==";
      };
    };
    "to-absolute-glob-2.0.2" = {
      name = "to-absolute-glob";
      packageName = "to-absolute-glob";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-2.0.2.tgz";
        sha1 = "1865f43d9e74b0822db9f145b78cff7d0f7c849b";
      };
    };
    "to-readable-stream-1.0.0" = {
      name = "to-readable-stream";
      packageName = "to-readable-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-readable-stream/-/to-readable-stream-1.0.0.tgz";
        sha512 = "Iq25XBt6zD5npPhlLVXGFN3/gyR2/qODcKNNyTMd4vbm39HUaOiAM4PMq0eMVC/Tkxz+Zjdsc55g9yyz+Yq00Q==";
      };
    };
    "to-through-2.0.0" = {
      name = "to-through";
      packageName = "to-through";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-through/-/to-through-2.0.0.tgz";
        sha1 = "fc92adaba072647bc0b67d6b03664aa195093af6";
      };
    };
    "to-utf8-0.0.1" = {
      name = "to-utf8";
      packageName = "to-utf8";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-utf8/-/to-utf8-0.0.1.tgz";
        sha1 = "d17aea72ff2fba39b9e43601be7b3ff72e089852";
      };
    };
    "uglify-js-3.6.0" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.6.0.tgz";
        sha512 = "W+jrUHJr3DXKhrsS7NUVxn3zqMOFn0hL/Ei6v0anCIMoKC93TjcflTagwIHLW7SfMFfiQuktQyFVCFHGUE0+yg==";
      };
    };
    "unc-path-regex-0.1.2" = {
      name = "unc-path-regex";
      packageName = "unc-path-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unc-path-regex/-/unc-path-regex-0.1.2.tgz";
        sha1 = "e73dd3d7b0d7c5ed86fbac6b0ae7d8c6a69d50fa";
      };
    };
    "unique-stream-2.3.1" = {
      name = "unique-stream";
      packageName = "unique-stream";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-stream/-/unique-stream-2.3.1.tgz";
        sha512 = "2nY4TnBE70yoxHkDli7DMazpWiP7xMdCYqU2nBRO0UB+ZpEkGsSija7MvmvnZFUeC+mrgiUfcHSr3LmRFIg4+A==";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "url-parse-lax-3.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-3.0.0.tgz";
        sha1 = "16b5cafc07dbe3676c1b1999177823d6503acb0c";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "validator-10.8.0" = {
      name = "validator";
      packageName = "validator";
      version = "10.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-10.8.0.tgz";
        sha512 = "mXqMxfCh5NLsVgYVKl9WvnHNDPCcbNppHSPPowu0VjtSsGWVY+z8hJF44edLR1nbLNzi3jYoYsIl8KZpioIk6g==";
      };
    };
    "value-or-function-3.0.0" = {
      name = "value-or-function";
      packageName = "value-or-function";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-or-function/-/value-or-function-3.0.0.tgz";
        sha1 = "1c243a50b595c1be54a754bfece8563b9ff8d813";
      };
    };
    "varint-0.0.3" = {
      name = "varint";
      packageName = "varint";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-0.0.3.tgz";
        sha1 = "b821de9b04b38b3cd22f72c18d94a9fb72ab3518";
      };
    };
    "vinyl-2.2.0" = {
      name = "vinyl";
      packageName = "vinyl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl/-/vinyl-2.2.0.tgz";
        sha512 = "MBH+yP0kC/GQ5GwBqrTPTzEfiiLjta7hTtvQtbxBgTeSXsmKQRQecjibMbxIXzVT3Y9KJK+drOz1/k+vsu8Nkg==";
      };
    };
    "vinyl-fs-3.0.3" = {
      name = "vinyl-fs";
      packageName = "vinyl-fs";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl-fs/-/vinyl-fs-3.0.3.tgz";
        sha512 = "vIu34EkyNyJxmP0jscNzWBSygh7VWhqun6RmqVfXePrOwi9lhvRs//dOaGOTRUQr4tx7/zd26Tk5WeSVZitgng==";
      };
    };
    "vinyl-sourcemap-1.1.0" = {
      name = "vinyl-sourcemap";
      packageName = "vinyl-sourcemap";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl-sourcemap/-/vinyl-sourcemap-1.1.0.tgz";
        sha1 = "92a800593a38703a8cdb11d8b300ad4be63b3e16";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xdg-basedir-3.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-3.0.0.tgz";
        sha1 = "496b2cc109eca8dbacfe2dc72b603c17c5870ad4";
      };
    };
    "xmlhttprequest-1.8.0" = {
      name = "xmlhttprequest";
      packageName = "xmlhttprequest";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.8.0.tgz";
        sha1 = "67fe075c5c24fef39f9d65f5f7b7fe75171968fc";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "yargs-parser-11.0.0" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "11.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-11.0.0.tgz";
        sha512 = "dvsafRjM45h79WOTvS/dP35Sb31SlGAKz6tFjI97kGC4MJFBuzTZY6TTYHrz0QSMQdkyd8Y+RsOMLr+JY0nPFQ==";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha1 = "c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9";
      };
    };
    "yazl-2.5.1" = {
      name = "yazl";
      packageName = "yazl";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yazl/-/yazl-2.5.1.tgz";
        sha512 = "phENi2PLiHnHb6QBVot+dJnaAZ0xosj7p3fWl+znIjBDlnMI2PsZCJZ306BPTFOaHf5qdDEI8x5qFrSOBN5vrw==";
      };
    };
  };
in
{
  "@antora/cli" = nodeEnv.buildNodePackage {
    name = "_at_antora_slash_cli";
    packageName = "@antora/cli";
    version = "2.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@antora/cli/-/cli-2.0.0.tgz";
      sha512 = "vgoGTRRFkPtKeMgGoBevYzK97DwT75rxUeE6yAtm50i7e/aIGoXFyCglaXdsyP4FAfENVqN+DWy3ZuKxhPfc7g==";
    };
    dependencies = [
      sources."@antora/playbook-builder-2.0.0"
      sources."@iarna/toml-2.2.3"
      sources."argparse-1.0.10"
      sources."camelcase-5.3.1"
      sources."camelcase-keys-5.2.0"
      sources."commander-2.20.0"
      (sources."convict-4.4.1" // {
        dependencies = [
          sources."json5-1.0.1"
        ];
      })
      sources."decamelize-1.2.0"
      sources."deep-freeze-0.0.1"
      sources."depd-1.1.2"
      sources."esprima-4.0.1"
      sources."js-yaml-3.13.1"
      sources."json5-2.1.0"
      sources."lodash.clonedeep-4.5.0"
      sources."map-obj-3.1.0"
      sources."minimist-1.2.0"
      sources."moment-2.22.2"
      sources."quick-lru-1.1.0"
      sources."sprintf-js-1.0.3"
      sources."validator-10.8.0"
      sources."yargs-parser-11.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The command line interface for Antora.";
      homepage = https://antora.org/;
      license = "MPL-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@antora/site-generator-default" = nodeEnv.buildNodePackage {
    name = "_at_antora_slash_site-generator-default";
    packageName = "@antora/site-generator-default";
    version = "2.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@antora/site-generator-default/-/site-generator-default-2.0.0.tgz";
      sha512 = "YMor7dPAef4Pqyxbz7/ZqS0k5haxtcIkmEAfTJpGthCtRhrYfOu2iH+ZntnKRCubNdSgs77CRYjpSjm43rQ7FQ==";
    };
    dependencies = [
      sources."@antora/asciidoc-loader-2.0.0"
      sources."@antora/content-aggregator-2.0.0"
      sources."@antora/content-classifier-2.0.0"
      sources."@antora/document-converter-2.0.0"
      sources."@antora/expand-path-helper-1.0.0"
      sources."@antora/navigation-builder-2.0.0"
      sources."@antora/page-composer-2.0.0"
      sources."@antora/playbook-builder-2.0.0"
      sources."@antora/redirect-producer-2.0.0"
      sources."@antora/site-mapper-2.0.0"
      sources."@antora/site-publisher-2.0.0"
      sources."@antora/ui-loader-2.0.0"
      sources."@babel/runtime-7.5.4"
      sources."@iarna/toml-2.2.3"
      sources."@sindresorhus/is-0.14.0"
      sources."@szmarczak/http-timer-1.1.2"
      sources."append-buffer-1.0.2"
      sources."argparse-1.0.10"
      sources."asciidoctor.js-1.5.9"
      sources."async-lock-1.2.2"
      sources."balanced-match-1.0.0"
      sources."base64-js-0.0.2"
      sources."benchmark-1.0.0"
      (sources."bl-2.2.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."bops-0.0.7"
      sources."brace-expansion-1.1.11"
      sources."buffer-crc32-0.2.13"
      sources."buffer-equal-1.0.0"
      sources."cache-directory-2.0.0"
      (sources."cacheable-request-6.1.0" // {
        dependencies = [
          sources."get-stream-5.1.0"
          sources."lowercase-keys-2.0.0"
          sources."pump-3.0.0"
        ];
      })
      sources."camelcase-5.3.1"
      sources."camelcase-keys-5.2.0"
      sources."clean-git-ref-1.0.3"
      sources."clone-2.1.2"
      sources."clone-buffer-1.0.0"
      sources."clone-response-1.0.2"
      sources."clone-stats-1.0.0"
      (sources."cloneable-readable-1.1.3" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."commander-2.20.0"
      sources."concat-map-0.0.1"
      sources."convert-source-map-1.6.0"
      (sources."convict-4.4.1" // {
        dependencies = [
          sources."json5-1.0.1"
        ];
      })
      sources."core-util-is-1.0.2"
      sources."crc-32-1.2.0"
      sources."decamelize-1.2.0"
      sources."decompress-response-3.3.0"
      sources."deep-freeze-0.0.1"
      sources."defer-to-connect-1.0.2"
      sources."define-properties-1.1.3"
      sources."depd-1.1.2"
      sources."diff-3.5.0"
      sources."diff-lines-1.1.1"
      sources."duplexer-0.1.1"
      sources."duplexer3-0.1.4"
      (sources."duplexify-3.7.1" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."end-of-stream-1.4.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."event-stream-3.3.4"
      sources."exit-on-epipe-1.0.1"
      sources."extend-3.0.2"
      sources."fd-slicer-1.1.0"
      (sources."flush-write-stream-1.1.1" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."from-0.1.7"
      sources."fs-extra-7.0.1"
      (sources."fs-mkdirp-stream-1.0.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      (sources."get-stream-4.1.0" // {
        dependencies = [
          sources."pump-3.0.0"
        ];
      })
      sources."git-apply-delta-0.0.7"
      sources."glob-6.0.4"
      sources."glob-parent-3.1.0"
      (sources."glob-stream-6.1.0" // {
        dependencies = [
          sources."glob-7.1.4"
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."globalyzer-0.1.4"
      sources."globrex-0.1.2"
      sources."got-9.6.0"
      sources."graceful-fs-4.2.0"
      (sources."gulp-vinyl-zip-2.1.2" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."handlebars-4.1.2"
      sources."has-symbols-1.0.0"
      sources."http-cache-semantics-4.0.3"
      sources."ignore-5.1.2"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-absolute-1.0.0"
      sources."is-buffer-1.1.6"
      sources."is-extglob-2.1.1"
      sources."is-glob-3.1.0"
      sources."is-negated-glob-1.0.0"
      sources."is-relative-1.0.0"
      sources."is-unc-path-1.0.0"
      sources."is-utf8-0.2.1"
      sources."is-valid-glob-1.0.0"
      sources."is-windows-1.0.2"
      sources."isarray-1.0.0"
      sources."isomorphic-git-0.47.0"
      sources."js-yaml-3.13.1"
      sources."json-buffer-3.0.0"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."json5-2.1.0"
      sources."jsonfile-4.0.0"
      sources."keyv-3.1.0"
      (sources."lazystream-1.0.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."lead-1.0.0"
      sources."lodash-4.17.14"
      sources."lodash.clonedeep-4.5.0"
      sources."lowercase-keys-1.0.1"
      sources."map-obj-3.1.0"
      sources."map-stream-0.1.0"
      sources."marky-1.2.1"
      sources."matcher-1.1.1"
      sources."mime-db-1.40.0"
      sources."mime-types-2.1.24"
      sources."mimic-response-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimatch-all-1.1.0"
      sources."minimist-1.2.0"
      sources."minimisted-2.0.0"
      sources."moment-2.22.2"
      sources."multi-progress-2.0.0"
      sources."neo-async-2.6.1"
      sources."nick-0.1.3"
      sources."normalize-path-2.1.1"
      sources."normalize-url-4.3.0"
      sources."now-and-later-2.0.1"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."once-1.4.0"
      sources."opal-runtime-1.0.11"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
        ];
      })
      (sources."ordered-read-streams-1.0.1" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."p-cancelable-1.1.0"
      sources."pako-1.0.10"
      sources."path-dirname-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."pause-stream-0.0.11"
      sources."pend-1.2.0"
      sources."pify-4.0.1"
      sources."prepend-http-2.0.0"
      sources."printj-1.1.2"
      sources."process-nextick-args-2.0.1"
      sources."progress-1.1.8"
      sources."pump-2.0.1"
      sources."pumpify-1.5.1"
      sources."queue-4.5.1"
      sources."quick-lru-1.1.0"
      sources."readable-stream-3.4.0"
      sources."regenerator-runtime-0.13.2"
      sources."remove-bom-buffer-3.0.0"
      (sources."remove-bom-stream-1.2.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."remove-trailing-separator-1.1.0"
      sources."replace-ext-1.0.0"
      sources."require-from-string-2.0.2"
      sources."resolve-options-1.1.0"
      sources."responselike-1.0.2"
      sources."safe-buffer-5.1.2"
      sources."sha.js-2.4.11"
      sources."simple-concat-1.0.0"
      sources."simple-get-3.0.3"
      sources."source-map-0.6.1"
      sources."split-0.3.3"
      sources."split2-3.1.1"
      sources."sprintf-js-1.0.3"
      sources."stream-combiner-0.0.4"
      sources."stream-shift-1.0.0"
      sources."stream-source-0.3.5"
      sources."string_decoder-1.2.0"
      sources."through-2.3.8"
      sources."through2-3.0.1"
      (sources."through2-filter-3.0.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."to-absolute-glob-2.0.2"
      sources."to-readable-stream-1.0.0"
      (sources."to-through-2.0.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."to-utf8-0.0.1"
      sources."uglify-js-3.6.0"
      sources."unc-path-regex-0.1.2"
      sources."unique-stream-2.3.1"
      sources."universalify-0.1.2"
      sources."url-parse-lax-3.0.0"
      sources."util-deprecate-1.0.2"
      sources."validator-10.8.0"
      sources."value-or-function-3.0.0"
      sources."varint-0.0.3"
      sources."vinyl-2.2.0"
      (sources."vinyl-fs-3.0.3" // {
        dependencies = [
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
          sources."through2-2.0.5"
        ];
      })
      sources."vinyl-sourcemap-1.1.0"
      sources."wordwrap-0.0.3"
      sources."wrappy-1.0.2"
      sources."xdg-basedir-3.0.0"
      sources."xmlhttprequest-1.8.0"
      sources."xtend-4.0.2"
      sources."yargs-parser-11.0.0"
      sources."yauzl-2.10.0"
      sources."yazl-2.5.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The default site generator pipeline for producing and publishing static documentation sites with Antora.";
      homepage = https://antora.org/;
      license = "MPL-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}